# Generated by Django 5.2.15 on 2026-06-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('foundation', models.DateField(null=True, verbose_name='date foundation')),
                ('website', models.URLField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ram', models.IntegerField(help_text='in GB')),
                ('memory_capacity', models.IntegerField(help_text='in GB or TB')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phoneapp.manufacturer')),
            ],
        ),
    ]
