# Generated by Django 5.2.15 on 2026-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in inches', max_digits=4, null=True),
        ),
    ]
